# -*- coding: utf-8 -*-
"""Random Number Finding Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMPedCU6KiiKghAa3XT1Yy-Px63mAwfu
"""

import math
import random
import time

def get_int_input(prompt, min_val=None, max_val=None):
    while True:
        try:
            val = int(input(prompt))
            if min_val is not None and val < min_val:
                print(f"Please enter a number greater than or equal to {min_val}.")
                continue
            if max_val is not None and val > max_val:
                print(f"Please enter a number less than or equal to {max_val}.")
                continue
            return val
        except ValueError:
            print("Invalid input. Please enter a valid integer.")

print(f"---------- Welcome To Random Number Finding Game ----------\n")
time.sleep(0.5)
print(f"Choose To Play With:")
time.sleep(0.4)
print(f"1. AI")
time.sleep(0.4)
print(f"2. Single Player")
time.sleep(0.4)
print(f"3. With Friend")

def ai():
  print("\n--- Choose AI Difficulty ---")
  print("1. Easy (AI is clumsy and makes random/imperfect guesses)")
  print("2. Medium (AI guesses randomly within known bounds)")
  print("3. Hard / Smart (AI uses optimal binary search - very tough!)")
  difficulty = get_int_input("Enter your choice (1-3): ", 1, 3)

  num = random.randint(0, 100)
  won = False
  count = 0
  countai = 0
  start = 0
  end = 100
  while not won:
    guess = get_int_input(f"\nEnter your guess between 0 and 100: ", 0, 100)
    if num == guess:
      print("\nYou Won!")
      time.sleep(0.5)
      print(f"Number is {num}")
      won = True
      break
    elif num > guess:
      print(f"Number is Greater than {guess}")
      start = max(start, guess + 1)
      count += 1
    else:
      print(f"Number is Smaller than {guess}")
      end = min(end, guess - 1)
      count += 1

    # AI's turn
    if start > end:
      start, end = min(start, end), max(start, end)

    if difficulty == 1:
      # Easy AI: 40% chance of making a completely random guess in [0, 100], 
      # otherwise guesses within a wider, less optimal range
      if random.random() < 0.4:
        guessai = random.randint(0, 100)
      else:
        guessai = random.randint(max(0, start - 15), min(100, end + 15))
    elif difficulty == 2:
      # Medium AI: Guesses randomly in the current refined [start, end] range
      guessai = random.randint(start, end)
    else:
      # Hard / Smart AI: Midpoint binary search
      guessai = (start + end) // 2

    print(f"\nAI is thinking...")
    time.sleep(1.0)
    print(f"AI guesses: {guessai}")
    time.sleep(0.5)

    if num == guessai:
      print("\nAI Won!")
      time.sleep(0.5)
      print(f"Number is {num}")
      won = True
      break
    elif num > guessai:
      print(f"Number is Greater than AI number {guessai}")
      start = max(start, guessai + 1)
      countai += 1
    else:
      print(f"Number is Smaller than AI number {guessai}")
      end = min(end, guessai - 1)
      countai += 1

  print(f"\nYour Number of Guesses: {count}")
  print(f"AI Number of Guesses: {countai}")

def sp():
  num = random.randint(0, 100)
  won = False
  count = 0
  while not won:
    guess = get_int_input(f"Enter your guess between 0 and 100: ", 0, 100)
    if num == guess:
      print("\nYou Won!")
      time.sleep(0.5)
      print(f"Number is {num}")
      won = True
      break
    elif num > guess:
      print(f"Number is Greater than {guess}")
      count += 1
    else:
      print(f"Number is Smaller than {guess}")
      count += 1
  print(f"\nNumber of Guesses: {count}")

def fp():
  num = random.randint(0, 100)
  won = False
  count1 = 0
  count2 = 0
  while not won:
    guess1 = get_int_input(f"Player 1 Enter your guess between 0 and 100: ", 0, 100)
    if num == guess1:
      print("\nPlayer 1 Won!")
      time.sleep(0.5)
      print(f"Number is {num}")
      won = True
      break
    elif num > guess1:
      print(f"Number is Greater than {guess1}")
      count1 += 1
    else:
      print(f"Number is Smaller than {guess1}")
      count1 += 1

    guess2 = get_int_input(f"Player 2 Enter your guess between 0 and 100: ", 0, 100)
    if num == guess2:
      print("\nPlayer 2 Won!")
      time.sleep(0.5)
      print(f"Number is {num}")
      won = True
      break
    elif num > guess2:
      print(f"Number is Greater than {guess2}")
      count2 += 1
    else:
      print(f"Number is Smaller than {guess2}")
      count2 += 1
  print(f"\nPlayer 1 Number of Guesses: {count1}")
  print(f"Player 2 Number of Guesses: {count2}")

choose = get_int_input("Enter your choice: ", 1, 3)
if choose == 1:
    print("AI is ready to play!")
    time.sleep(0.5)
    ai()
elif choose == 2:
    print("Game Started!\n")
    time.sleep(0.5)
    sp()
elif choose == 3:
    print(f"Play With Friend\n")
    time.sleep(0.5)
    fp()

